### ISSUE TITLE
Suggest moving UserAgent beneath Google::Client::Lib

### ISSUE THREAD

**Issue by pscott-au** [sdondley/moo-google#17]
Just a suggestion - Google::WebService::UserAgent is not really stand-alone usable - would it be better beneath Client ?

**Comment by sdondley** [comment]
Probably, yeah. It's been in the back of my mind that how the modules are arranged in the library don't really make sense. I haven't take a hard look at it, yet.

**Comment by pscott-au** [comment]
see my tar bundle to see how I've done this and removed Server.pm from the lib. Also refactored to pass perlcritic harsh. NB I have a perlstyle that differs from your - perhaps you could include your own perltidyrc in your repo.

Mine is
```
#  -pbp     # Start with Perl Best Practices - not sure how to drive and cuddles my braces
-w       # Show all warnings
-iob     # Ignore old breakpoints
-l=140    # 80 characters per line
-mbl=2   # No more than 2 blank lines
-i=2     # Indentation is 2 columns
-ci=2    # Continuation indentation is 2 columns
-vt=0    # vertical tightness
-pt=0    # parenthesis tightness
-bt=0    # brace tightness
-sbt=2   # square bracket tightness
-wn      # Weld nested containers
-isbc    # Don't indent comments without leading space
-sbl     # sub-brace on new line
-bl      # Opening Braces Left
-b -bext='/' # operwrite the file and delete backup if no errors
```

**Comment by sdondley** [comment]
I don't use perlcritic or perltidy myself. But they can serve as arbiters when there is a question as to what approach to take to end holy wars. For example, I'm a two space indent guy myself but would cede to 4 if that's what PBP says is good.

**Comment by pscott-au** [comment]
perhaps you should remove the references to them in your dist.ini if you aren't looking to use them

**Comment by sdondley** [comment]
I've never seen them really do anything. I've never used them or even read the docs about those plugins. But I will just leave them in to see try to figure out if they add any value.

**Comment by pscott-au** [comment]
also - the point isn't that PBP is the authority cart-blanche - Damian Conway will agree that it's more about remaining constant rather than imposing your preferences for stylistic matters. Variance can be easily accomodated by personalising your toolset to avoid what you describe as 'holy wars' to allow each to operate in the style that they are most productive in rather than imposing your preferences on others. So rather than wasting discussion on brace style you can focus on the code.

**Comment by sdondley** [comment]
PBP isn't really the ideal standard and, from what I understand, outdated. There are other more accepted standards out there but I forget what they are. I am of the opinion there should be one standard coding style per project. It's not hard to switch and it's all pretty arbitrary. It's not like the difference between bowling left handed or right handed where your brain is wired to do certain thing. It's more like the difference between learning simple table manners for different cultures and it helps to be well versed on all the different practices.

**Comment by pscott-au** [comment]
I suggest that if you use perltidy that you don't need to impose your idea
of manners onto others.

**Comment by sdondley** [comment]
I think "impose" is a very bad word to use. If I show up at a Japanese home, I take my shoes off. I don't feel the host is "imposing" on me in any way.

**Comment by pscott-au** [comment]
as a counter example - If I pronounce film differently from you I don't
expect you to correct me and expect me to say it the way you do. The
meaning is clear and you can interpret it with minimal effort.

**Comment by sdondley** [comment]
Well, compound the problem by 20 different developers using their own style. You have a big, messy problem on your hands.

**Comment by pscott-au** [comment]
No - each contributor runs perltidy and whatever style is used by others
gets instantly converted to their personal preferences - is very cool.

**Comment by sdondley** [comment]
Oh, right. I misinterpreted what you said in your earlier comment to mean I should get rid of perltidy so as not to impose on others.

**Comment by pscott-au** [comment]
No - I was trying to suggest either adopt it and ease back on the
opinionated style or don't use it, remove it from the config.ini and then
define your style that you require other to adopt.

**Comment by sdondley** [comment]
Well, it does no good to submit code with the pure objective of changing the style if it's going to be overwritten by a bot anyway.

**Comment by pscott-au** [comment]
except that it lower barriers to entry for the contributor who is then free
to code in their own style without worrying about the package owners edicts.

**Comment by pscott-au** [comment]
ie - if my code base is styled how I prefer I can still pull your code in
as you can with mine and instantly make it suit your own preferences.

**Comment by sdondley** [comment]
But if you pull in my upstream code generated by perltidy, it will not be to your liking unless you run it through your version of perltidy afterwards.

**Comment by pscott-au** [comment]
yes - because I respect your right to style to your own preferences and I
am willing to run perltidy to make it match mine.
There are consequences of course - you github diffs get ugly etc. But you
could include the package standard perltidyrc in the rc and then encourage
ppl to run the build against that so that it remains consistent to your
preferences when handling git pulls etc. But this overhead is vastly
preferable to spending time debating personal stylistic preferences.

**Comment by sdondley** [comment]
Then everyone will need to use Dist::Zilla.

So I go back to my original argument. When in Rome, do as the Romans do. Makes things run smoothly. It's all arbitrary and is easy to learn a different style.

**Comment by pscott-au** [comment]
after 10 years using my style - reading your stylistic preferences hurts my
eyes. Not that mine is better but it's what I work most efficiently with.
If you insist that I need to reverse engineer your stylistic preferences
then create a perltidyrc file to represent these then use that before
sharing any code then you are creating an unnecessary barrier to entry. The
Romans can GGF, they're dead.

**Comment by sdondley** [comment]
Except your style is not generally accepted perl style. In my almost 20 years of using Perl, I have never seen c-style braces used, except maybe by people new to Perl.

I can also tell you that I switch my style based on what is generally accepted by the wider community and generally accepted standards. If I program in C and the C book uses C-style brackets, I use C-style brackets.

**Comment by pscott-au** [comment]
and that is your choice - don't make it mine.

**Comment by sdondley** [comment]
I won't. When you are working on your own project you can code naked for all I care. When you work collaboratively with others, there are generally acceptable rules.

Example: https://01.org/linuxgraphics/gfx-docs/drm/process/coding-style.html

**Comment by pscott-au** [comment]
but we're getting off topic - i was just raising you inclusion of reference to tool you don't use - you can set you repo policies however you like.

**Comment by pscott-au** [comment]
i don't want to accept those rules so I won't - you are not obliged to streamline you collaboration processes either so don't

**Comment by sdondley** [comment]
So you leave your shoes on when you visit a Japanese household?

**Comment by sdondley** [comment]
This is an interesting discussion. But to be honest, it's kind of like arguing whether the sky is blue or not. It seems clear to me that adhering to a coding style has definite advantages for producing a better quality final product. I would be surprised if any successful large-scale project let developers just do their own thing. Beyond "I want to do what I want because it makes me feel comfortable," I don't see any other merit. My argument is, "sacrifice a wee tiny bit for what makes you feel comfortable for the good of the larger project."

**Comment by pscott-au** [comment]
agreed - you continue to conflate issues to draw into arguments - the point was minor and simple. I enquired about your inclusion of PERCRITIC in dist.ini and you confirmed that you don't use it but that you don't think it should be removed because you wish to evaluate it. Efforts to discuss it's functionality led to an argument where you clearly are insistent on retaining authority as you interpret ebst practice contrary to common usage. That is ok - it's your repo. There's no need to discuss my feet or what I'm wearing - I raised an issue - you dismissed it as not something you think is worth exploring with me that you intend to look into at some time in the future. All this in with a code suggestion that you refuse to discuss in any meaningful way so I will leave it there for others to consider if they find it useful. I'm not a project resource I'm simply a passer in the night - there's no need to convince me I'm wrong and you don't need to heed any advice I give - just ease back on insisting the conflate into an argument and keep to the issues where possible if you can so that you don't chase away ppl who are offering to help.
You've already made it clear that you won't accept collaboration through Github without complying with your unpublished policies being created on the fly and continue to reference external authority to justify choices without providing references to them or parts of them that are being applied with reasoning to allow clarification or meaningful discussion. Essentially you are imposing authority in an area that you know little about in practice and referring to large scale projects generally without any understanding of how the application of their unspecified standards either apply or solve specific obstacles. You have stated that you are more interested in exploring the best practices of large projects above fixing the code so I guess in a way it should be expected - is just a shame that you are creating barriers to entry  from the outset  on a library that could and should evolve to be incredibly useful to many in the community who are fumbling with the current offerings. So long as you insist on placing you learning above the project you are not allowing any real progress unless ppl adhere to your arbitrary appeals to uncited authority and you insistence that it's ok to ignore them where you don't understand them.

**Comment by sdondley** [comment]
Like I've already said, I'm interested in adhering to best practices as much as possible. I've not heard any compelling reason to let people contribute whatever code style they want. I could definitely be wrong and I'm willing to listen. If you can point to a successful large scale project that does, I'd be interested in hearing about it.

**Comment by pscott-au** [comment]
So if you insist that any contribution adheres to your best-practice style is it too much to ask that you describe or even better provide a specification or reference to it rather than just ignoring any code because it's not the way you do it.

Please cite your references if you are imposing them on all contributors rather than the simple appeal to authority of 'big projects'
You previously point to PBP and percritic then when they were applied you say that there are better more modern practices and you don't consider PBP more than a starting reference point. Similarly you cite the tools of dzil but then dismiss them because by your own admission you don't know how they work.

maybe draw a leaf from https://mojolicious.org/perldoc/Mojolicious/Guides/Contributing

**Comment by pscott-au** [comment]
this is a perl library not a major project - you aren't expecting a team of ppl to be working full time on this. A library isn't a vanity space - if you are being authoritarian to retain scope of all activity how does it help the library evolve.

**Comment by sdondley** [comment]
I've consistently offered to let PBP or some other standard be the arbiter.

Please see https://github.com/sdondley/WebService-Google-Client/blob/master/README_4_CONTRIBUTORS.md

If you can't offer a compelling reason other than "I don't like to do it that way" then I'm simply not going to change them. That's it.

**Comment by pscott-au** [comment]
You've already pushed my out of github pulls by trying to enforce a standard that I can't work with - now you are rejecting any attempt to engage even in discussion about specific technical issues without falling back to style / best practice and your authority.

**Comment by sdondley** [comment]
I don't know what else to you, man. I've offered to follow a neutral arbiter like PBP or something similar. This isn't about my coding style. This is about following *one* coding style and one that is a largely accepted standard.

**Comment by pscott-au** [comment]
my code follows PBP and complies with perlcritic --harsh - yours does not - but you refuse to look at because my tab size and brace alignment do not comply?

**Comment by pscott-au** [comment]
maybe i'm taking you too seriously - was hoping we could do something here but my personality does not seem compatible with yours - I'll try to find something better to do with my time then incite you to argue.

**Comment by sdondley** [comment]
If having braces on a separate line is going to lead to a bunch of unnecessarily large diffs then yeah, that's a pretty bad idea.

**Comment by pscott-au** [comment]
muppet

**Comment by sdondley** [comment]
Ah, now we are reduced to insults. I'll leave you with this from PBP:

"Adopting a coherently designed approach to code layout, and then applying that approach consistently across all your coding, is fundamental to best practice programming. Good layout can improve the readability of a program, help detect errors within it, and make the structure of your code much easier to comprehend. Layout matters.

But most coding styles—including the four mentioned earlier—confer those benefits almost equally well. So while it's true that having a consistent code layout scheme matters very much indeed, the particular code layout scheme you ultimately decide upon … does not matter at all!All that matters is that you adopt a single, coherent style; one that works for your entire programming team. And, having agreed upon that style, that you then apply it consistently across all your development."

So Damian Conway, the author of PBP, will serve as our arbiter. And he says precisely what I've been saying.

**Comment by pscott-au** [comment]
Yes - worked with Damian - really nice guy. You're comments and quote
remain meaningless and lack any context - you are arguing now for the sake
of it. I reiterate - you code doesn't go anywhere near PBP compared to mine
- you continue to insist on brace style - I don't care about brace style -
enforce it all you like. You also previously stated that PBP is redundant -
just pick a standard and stick with it.

**Comment by sdondley** [comment]
Ok, well, I'm done with engaging with toxic people as is evident by your "muppet" comment above which you have deleted. Enjoy your day.

**Comment by pscott-au** [comment]
thank you - now I can comment for ppl who aren't toxicly quite so argumentative and intractable and are open to reasonable dialogue.

Consider the workflow you are proposing:
user of lib want to contribute
they are asked to checkout the dev branch make changes then trim out all the commits so it's a single file then submit a pull request into dev. They must retain the original style or it will be rejected as despite the perltidy reference in config.ini  no additional detail is provided to allow offline development in any other style.
if there code passes this hurdle and the dev branch hasn't been modified since their checkout then it will be included as a distinct branch and the code merged into the dev branch untiul some point in the future when the author determines it is ready for release. They will then be expected to re-checkout the dev branch again once the changes are merged to start again so that their changes can be pushed into the branch created for them. 

This might work if you have a release cycle and many devs but is it any way to run a cpan module?

**Comment by sdondley** [comment]
Please, I'm asking nicely, just go away. You're input is no longer desired. Thanks.

**Comment by pscott-au** [comment]
clearly it never was
